[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "churn-prediction-ml"
version = "0.1.0"
description = "A Streamlit-based churn prediction ML app"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
  {name = "Alok Mahadev Tungal", email = "your_email@example.com"}
]

dependencies = [
    "streamlit==1.38.0",
    "pandas==2.2.2",
    "numpy==1.26.4",
    "scikit-learn==1.5.1",
    "plotly==5.22.0",
    "matplotlib==3.9.2",
    "seaborn==0.13.2",
    "joblib==1.4.2",
    "shap==0.46.0",
    "numba==0.59.1",
    "llvmlite==0.42.0",
]

[tool.setuptools.packages.find]
where = ["."]

